---
title: "RWorksheet_de la Cruz-Hanz#4a"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
ShoeSizeDF <- data.frame(
  Shoe_size = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,
               7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,
               10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,
               13.0),
  
  Height = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,
             72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,
             59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,
             72.0,70.0,69.0,70.0),
  Gender = c("F","F","F","F","M","F","F","F","M","F","M","F",
             "M","M","M","M","F","F","M","F","F","M","M","F",
             "M","M","M","M")
  
)
ShoeSizeDF
```
```{r subset male and female}
subsetMale <- ShoeSizeDF[ShoeSizeDF$Shoe_size &  ShoeSizeDF$Height & ShoeSizeDF$Gender == "M",]
subsetMale
subsetFemale <- subset(ShoeSizeDF, Gender == "F")
subsetFemale
```

```{r mean of  shoe size}
SizeMeanMale<- mean(subsetMale$Shoe_size) 
SizeMeanFemale <- mean(subsetFemale$Shoe_size) 
totalSizeMean <- mean(ShoeSizeDF$Shoe_size)
            
cat("The mean of shoe sizes for males is:", SizeMeanMale)
cat("\nThe mean of the shoe sizes for females is:",SizeMeanFemale)
cat("\nThe total mean for shoe sizes is: ", totalSizeMean)


```
```{r mean of height}
HeightMeanMale <- mean(subsetMale$Height)
HeightMeanFemale <- mean(subsetFemale$Height)
totalHeightMean <- mean(ShoeSizeDF$Height)
  
cat("The mean for height of males is:", HeightMeanMale)
cat("\nThe mean of the height of females is:",HeightMeanFemale)
cat("\nThe total mean for height is: ", totalHeightMean)
cat("\n\nYes, there is a relationship between height and mean. The higher the height the bigger the shoe sizes")
```
```{r months}
months <- c("March","April","January","November","January",
            "September","October","September","November","August",
            "January","November","November","February","May","August",
            "July","December","August","August","September","November",
            "February","April")

factor_months_vector <- factor(months)

factor_months_vector

```
```{r summary}
MonthSummary <- summary(months)
MonthSummary
FactorMonthSummary <- summary(factor_months_vector)
FactorMonthSummary
cat("\nYes, summary of both vectors are useful. They show different information such as the length, the class and modes and the values under that month")
```
```{r direction}
DirectionDF = data.frame(
              Direction = c("East","West","North"),
              Frequency = c(1,4,3)
              
)
DirectionDF
new_order_data <- factor(DirectionDF,levels = c("East","West","North"))
print(new_order_data)
```

```{r readtable}
read.table(file="import_march.csv",sep = ",",header = TRUE, as.is=TRUE )
```
```{r numbers 1 to 50}

userInput <- readline(prompt="Enter a number: ")

if (as.numeric(userInput) < 1 || as.numeric(userInput) > 50) {
  print("The number selected is beyond the range of 1 to 50")
} else if (as.numeric(userInput) == 20) {
  print("TRUE")
} else {
  print(userInput)

}
```

```{r change}
total_amount <- as.numeric(readline(prompt = "Enter the total amount: "))

if (total_amount >= 1000) {
  num_1000_bills <- total_amount %/% 1000
  total_amount <- total_amount %% 1000
  cat("Number of 1000 peso bills:", num_1000_bills, "\n")
}
if (total_amount >= 500) {
  num_500_bills <- total_amount %/% 500
  total_amount <- total_amount %% 500
  cat("Number of 500 peso bills:", num_500_bills, "\n")
}
if (total_amount >= 200) {
  num_200_bills <- total_amount %/% 200
  total_amount <- total_amount %% 200
  cat("Number of 200 peso bills:", num_200_bills, "\n")
}
if (total_amount >= 100) {
  num_100_bills <- total_amount %/% 100
  total_amount <- total_amount %% 100
  cat("Number of 100 peso bills:", num_100_bills, "\n")
}
if (total_amount >= 50) {
  num_50_bills <- total_amount %/% 50
  total_amount <- total_amount %% 50
  cat("Number of 50 peso bills:", num_50_bills, "\n")
}

```

```{r grades}
student_grades <- data.frame(
  Name = c("Annie","Thea","Steve","Hanna"),
  Grade_1 = c(85,65,75,95),
  Grade_2 = c(65,75,55,75),
  Grade_3 = c(85,90,80,100),
  Grade_4 = c(100,90,85,90)
)
  
student_grades
student_grades$Average <- (student_grades$Grade_1 + student_grades$Grade_2 + student_grades$Grade_3 + student_grades$Grade_4) / 4

achievers <- subset(student_grades, Average == 90, select = c("Name", "Average"))
achievers


```
```{r test difficulty}
Tests <- which(rowMeans(student_grades[, 2:5]) < 80)
output <- if (length(Tests) > 0) {
  if (Tests == 1) {
    paste("The 1st test was difficult.")
  } else if (Tests == 2) {
    paste("The 2nd test was difficult.")
  } else if (Tests == 3) {
    paste("The 3rd test was difficult.")
  } else {
    paste("The ", Tests, "th test was difficult.")
  }
} else {
  "No test was difficult."
}
output
```
```{r max grade }  
# Creating the data frame
student_grades$Highest <- pmax(pmax(student_grades$Grade_1, student_grades$Grade_2), pmax(student_grades$Grade_3, student_grades$Grade_4))

high_achievers <- subset(student_grades, Highest > 90, select = c("Name", "Highest"))

max_grade <- paste(high_achievers$Name,"'s highest grade this semester is ", high_achievers$Highest, ".")
cat(max_grade)  
```
  
  
  
  