---
title: "Rworksheet_de la Cruz-Hanz #3a"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2023-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LettersVector}
#printing lowercase and uppercase letters
LETTERS
letters
```

```{r firstElevenLetters}
#first eleven letters
firstEleven <- LETTERS [1:11]
firstEleven
```

```{r oddNumberLetters}
#letters that are in the odd numbers
odd_letters <- LETTERS[seq(1, length(letters), by = 2)]
odd_letters
```

```{r vowels}
#vowels
vowels <- LETTERS[c(1,5,9,15,21)]
vowels 
```

```{r lastFive}
#last five lowercase letters
lastFive <- letters[22:26]
lastFive
```

```{r lettersBetween}
#letters in the index 15 to 24
lettersBetween <- letters [15:24]
lettersBetween
```

```{r averageTemp}
#average temparture of each city
averageTemp <- c("Tuguegarao City" = 42  ,"Manila" = 39 ,"Iloilo City" = 34, "Tacloban" = 34, "Samal Island" = 30  , "Davao City" = 27)
averageTemp
```
```{r city}
#city vector
city <- c("Tuguegarao City" ,"Manila","Iloilo City" , "Tacloban" , "Samal Island"  , "Davao City")
city

```

``` {r temp}
#temperature vector
temp <- c(42,39,34,34,30,27)
temp
```
```{r cityDataframe}

cityTemp <- data.frame(
  City_Name = (city),
  Temp = (temp))
cityTemp

```
```{r functions}
#changing column names using names() 
names(cityTemp) <- c("City", "Temperature")
cityTemp
```

```{r strCitytemp}
#str(cityTemp)
str(cityTemp)
```

```{r access row 3 and 4}
#access row 3 and 4
cityTemp[3:4,1:2]
```
```{r lowest and max temp}
#lowest and max temp of the cities 
minTemp <- min(cityTemp$City)
maxTemp <- max(cityTemp$City)
maxTemp
minTemp
```

```{r creating a matrix}
#matrix with 2 rows
matrix_1 <- matrix(c(5,6,7,4,3,2,1,2,3,7,8,9),nrow = 2)
matrix_1
```
```{r creating a matrix 2}
#creating a matrix with 3 rows and 2 columns
matrix_2 <-matrix(data = c(3,4,5,6,7,8),3,2)
matrix_2
```
```{r diagonal}
diagmatrix <- diag(1,nrow = 6,ncol = 5)
diagmatrix
```
```{r diagonal 2}
diagmatrix2 <- diag(6)
diagmatrix2
```
```{r matrix 3}
matrix_3 <- matrix(c(1:8,11:14),3,4)
matrix_3
```
```{r matrix 4}
matrixMulti <- matrix_3 * 2
matrixMulti
```
```{r matrix 5}
matrixRow2 <- matrixMulti [2,1:4]
matrixRow2 
```

```{r matrix 6}
matrixRow3Col2and3 <- matrixMulti [3,c(2,3)]
matrixRow3Col2and3
```
``` {r matrix column 4}
matrixColumn4 <- matrixMulti [1:3,4]
matrixColumn4
```

```{r naming rows and  columns }
#naming rows and columns
rownames(matrixMulti)[1:3] <- c("isa","dalawa","tatlo")

colnames(matrixMulti)[1:4] <- c("uno","dos","tres","quatro")
matrixMulti
```

```{r changing dimensions}
dim(matrix_3) <- c(6,2)
matrix_3
```
```{r arrays}
#creating an array with 2 rows, 4 columns and 3 dimensions
vector1 <- c(1,2,3,6,7,8,9,0,3,4,5,1)
array1 <- array(vector1, dim = c(2,4,3))
array1
```
```{r dimensions of array}
dimOfArray1 <- dim(array1)
dimOfArray1 #array has 2columns 4rows and 3 dimensions
```

```{r renaming columns rows and dimension names}
#renaming columns rows and dimension names

dimnames(array1) <- list(letters[1:2],LETTERS[1:4], c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
array1
```
